sonar.host.url=http://192.168.10.6:9005
sonar.token=sqa_7c73c40ecd845afc3aca18de0617895666277211
sonar.projectDescription=Altas-Catalog Connector for Nexus Repository Manager
sonar.projectKey=acamposm:atlas-nexus-connector
sonar.projectName=Atlas Nexus Repository Manager Connector
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/coverage/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml