# SonarQube Project Configuration
sonar.projectDescription=Altas-Catalog Connector for Nexus Repository Manager
sonar.projectKey=acamposm:atlas-nexus-connector
sonar.projectName=Atlas Nexus Repository Manager Connector
sonar.projectVersion=0.1.0

# Path to source directories
sonar.sources=src
sonar.tests=tests

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Language
sonar.language=php

# Test execution and coverage reports
sonar.php.coverage.reportPaths=build/coverage/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml

# Exclusions
sonar.exclusions=vendor/**, build/**, .phpunit.cache/**